version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx_tomcat
    ports:
      - "80:1234"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tomcat1
      - tomcat2
      - tomcat3
    
  tomcat1:
    image: tomcat
    container_name: tomcat01
    volumes:
      - ./tomcat01:/usr/local/tomcat/webapps/ROOT

  tomcat2:
    image: tomcat
    container_name: tomcat02
    volumes:
      - ./tomcat02:/usr/local/tomcat/webapps/ROOT

  tomcat3:
    image: tomcat
    container_name: tomcat03
    volumes:
      - ./tomcat03:/usr/local/tomcat/webapps/ROOT
  
